### ISSUE TITLE
Support for armv6/7

### ISSUE THREAD

**Issue by agarthetiger** [gantsign/ansible-role-golang#167]
Hi,

I'd like to use this role for several Raspberry Pi 4b hosts running the 32bit Raspberry Pi OS. I'm happy to do the work and raise a PR but I wanted to check something first.

The architecture is arm7l which is what ansible_architecture also reports, however Golang only have an armv6l build. This version of Go works fine on the Pi 4b under Raspbian, however as the current role stands it would mean adding vars/main-armv7l.yml which would contain `golang_redis_filename: 'go{{ golang_version }}.linux-armv6l.tar.gz'`. Before I spend time creating all the sha files for armv6l and raise a PR does this sound ok? 

Also, I don't suppose you have a python script or similar for scraping all the sha checksums and creating the files?

**Comment by freemanjp** [comment]
Hi @agarthetiger, sounds like a reasonable approach to me. As for the SHAs I don't think there's much point in adding a lot of historic versions, the latest supported patches should be sufficient (1.15.3 and 1.14.10). FYI if you choose to contribute you'll need to agree to the CLA: https://gist.github.com/freemanjp/11bf7ab7af7edcd07eed0ab01c1b04f5 (there's nothing you need to do now, https://cla-assistant.io will prompt you to agree when you submit the pull request).

**Comment by agarthetiger** [comment]
Thanks, I've raised a PR for this now and agreed to the CLA. I'm happy to close this and follow up on the PR if needed. Thanks :)
