### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by damianoneill** [gantsign/ansible-role-golang#183]
Hi, when running the role with ansible 2.10.4 I get the following warning. 

```console
TASK [gantsign.golang : download Go language SDK] **************************************************************************************************************
[DEPRECATION WARNING]: The parameter "sha256sum" has been deprecated and will be removed, use "checksum" instead. This feature will be removed from ansible-
base in version 2.14. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Just raising in case you haven't seen it.  Thanks for the role, very useful.

**Comment by freemanjp** [comment]
@damianoneill thanks for reporting this issue, you can find the fix in version [2.8.0](https://github.com/gantsign/ansible-role-golang/releases/tag/2.8.0) of this role.
